# Generated by Django 4.2.1 on 2023-05-13 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_productionline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='style',
            name='Buyer',
        ),
        migrations.AddField(
            model_name='style',
            name='barcode',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
