# Generated by Django 4.2.1 on 2023-05-13 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_orderqty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='style',
            name='BuyerName',
            field=models.CharField(max_length=225, unique=True),
        ),
    ]
