# Generated by Django 4.2.1 on 2023-05-13 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_style_buyername'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderqty',
            old_name='Date',
            new_name='date',
        ),
        migrations.AddField(
            model_name='orderqty',
            name='box_charge',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orderqty',
            name='import_export_charge',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orderqty',
            name='making_charge',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orderqty',
            name='poly_bag',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orderqty',
            name='sewing_thread',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
