# Generated by Django 4.2.1 on 2023-05-15 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_rename_date_orderqty_date_orderqty_box_charge_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='style',
            name='BuyerName',
            field=models.CharField(max_length=225),
        ),
    ]
