# Generated by Django 4.2.1 on 2023-05-15 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_orderqty_updated_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderqty',
            old_name='updated_date',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='orderqty',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
