# Generated by Django 4.2.1 on 2023-05-16 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_rename_updated_date_orderqty_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderqty',
            name='buyer',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='orderqty',
            name='style',
            field=models.CharField(max_length=255),
        ),
    ]
