# Generated by Django 4.2.1 on 2023-05-16 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_orderqty_buyer_alter_orderqty_style'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderqty',
            name='accETA',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderqty',
            name='delivery',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orderqty',
            name='fabricETA',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderqty',
            name='serial_number',
            field=models.CharField(default=5, max_length=255),
            preserve_default=False,
        ),
    ]
