# Generated by Django 4.2.1 on 2023-05-16 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_orderqty_acceta_orderqty_delivery_orderqty_fabriceta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='Vendor',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='orderqty',
            name='cmp',
            field=models.FloatField(default=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderqty',
            name='cmp_condition',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderqty',
            name='item',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='orderqty',
            name='md_charge',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='orderqty',
            name='vendor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
