# Generated by Django 4.2.1 on 2023-05-16 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_buyer_vendor_orderqty_cmp_orderqty_cmp_condition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='style',
            name='Vendor',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
