# Generated by Django 4.2.1 on 2023-05-17 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_style_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderqty',
            name='accETA',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='orderqty',
            name='delivery',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='orderqty',
            name='fabricETA',
            field=models.DateField(),
        ),
    ]
