# Generated by Django 4.2.1 on 2023-05-27 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_alter_orderqty_acceta_alter_orderqty_delivery_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line', models.CharField(max_length=255)),
                ('style', models.CharField(max_length=255)),
                ('input_qty', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
