# Generated by Django 4.2.1 on 2023-05-27 07:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_productioninput'),
    ]

    operations = [
        migrations.AddField(
            model_name='productioninput',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
