# Generated by Django 4.2.1 on 2023-06-13 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_dailyproductionouput'),
    ]

    operations = [
        migrations.AddField(
            model_name='productioninput',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
