# Generated by Django 4.2.1 on 2023-06-17 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_productioninput_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyproductionouput',
            name='wok_hr',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
