# Generated by Django 4.2.1 on 2023-06-18 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_dailyproductionouput_wok_hr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyproductionouput',
            name='wok_hr',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
