# Generated by Django 4.2.1 on 2023-06-23 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_productionline_daily_target'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyProductionLineMenPower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line', models.CharField(max_length=225)),
                ('num_operator', models.PositiveIntegerField(default=0)),
                ('num_helper', models.PositiveIntegerField(default=0)),
                ('date', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
