# Generated by Django 4.2.1 on 2023-06-27 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_dailyproductionlinemenpower'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyproductionouput',
            name='menpower',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
